# Generated by Django 4.0.4 on 2022-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='portfolio_images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='portfolio', to='weblabs.category')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'Portfolio',
                'db_table': 'Portfolio',
            },
        ),
    ]
