# Generated by Django 4.0.4 on 2022-05-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
